class: ProximalBertPruningManager
config_file: bert_base_sparsity_config.example.yaml
init_weights_path: nvidia-bert-base-uncased-pytorch_model.bin

initial_rho: 0.001
rho_num: 4
initial_lambda: 0.0001
cross_x: 1
cross_f: 1
update_freq: 300 # 30
lr: 0.006
admm_steps: 1500  # 300
retrain_steps: 3000 # 300

sparsity_type: threshold
arch: bert_base_uncased
optimizer_type: NVLAMB
dataset_type: EnwikiBookcorpus
save_dir: test_pretrain_admm_rho1e-3_lambda1e-4_1x1_lr6e-3_rhos4_steps6000
overwrite: True
admm_ckpt_steps: 600 # 200
retrain_ckpt_steps: 600 # 200

fp16: True
tensorboard_logdir: tb_logs_rho1e-3_lambda1e-4_1x1_lr6e-3_rhos4_steps6000
tensorboard_json_path: tb_logs_rho1e-3_lambda1e-4_1x1_lr6e-3_rhos4_steps6000/all_scalars.json