class: ProximalBertPruningManager
config_file: bert_base_sparsity_config.example.yaml
init_weights_path: nvidia-bert-base-uncased-pytorch_model.bin

initial_rho: 0.0001
rho_num: 1
proximal_lambda: 1
update_freq: 100
lr: 0.004
admm_steps: 3000
retrain_steps: 3000

sparsity_type: threshold
arch: bert_base_uncased
optimizer_type: NVLAMB
dataset_type: EnwikiBookcorpus
save_dir: None
overwrite: False
admm_ckpt_steps: 500
retrain_ckpt_steps: 500

tensorboard_logdir: tb_logs
tensorboard_json_path: tb_logs/all_scalars.json